### ISSUE TITLE
RESOURCE SECURITY HYGIENE section of Security Center, select Compute & apps no longer appears to exist.

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#1]
# Lab/Demo: 04
#### Step: 01

Description of issue
**RESOURCE SECURITY HYGIENE section of Security Center, select Compute & apps is not visible as an option. 
It appears this may have been renamed "Inventory."**
![2020-11-06_135506](https://user-images.githubusercontent.com/62302805/98404291-4b637a00-2038-11eb-8305-25acdebb3e20.jpg)

Repro steps:
https://github.com/MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS/blob/master/Instructions/Labs/LAB_04_Using_Azure_Security_Center_in_hybrid_scenarios.md

**Comment by TJGitHubUser** [comment]
Ex 2, Task 3: this whole task has been updated.
