### ISSUE TITLE
Lab 3 Exercise 3 Task 1 Step7 Cert Failure

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#10]
# Module: 3
### Exercise3: 
Task 1
#### Step: 7

After running ./Deploy-WACAzVM.ps1 @scriptParams
at end I get this error. I have tried it twice using EastUS region

![errorLab3-ex3-t1-step7](https://user-images.githubusercontent.com/30813190/103376299-e6f5f180-4aa1-11eb-8de5-27c47bff02bf.png)

**Comment by simplescripter** [comment]
I get the same error. I've tried using both a hosted lab environment and my own subscription with the same results. Initially I thought error might relate to PowerShell's use of TLS 1.0 by default, but that doesn't seem to be the problem, or at least not the only problem. After the error, the ws2019-wac-vm has been provisioned (apparently using 2016 Datacenter instead of 2019 for some reason), but I can't connect to it manually, either through TLS or RDP, even though NSG rules allow both.

**Comment by djcmct** [comment]
There appears to be a number of issues running Deploy-WACAzVM.ps1, too many for my limited scripting capabilities to handle, so had to get a little more manual....

(I'm not suggesting the detail below as a fix to the lab, just the easiest way i found without fixing the script.)

To deploy  ws2019-wac-vm with the correct OS and size i modified Ex 3 Task1 Step 6 to include a couple of variables declared in step 5 
$scriptParams = @{
  ResourceGroupName = $rgName
  Name = 'ws2019-wac-vm'
  VirtualNetworkName = $vnetName
  SubnetName = $subnetName
  GenerateSslCert = $true
  **_size = $size
  image = $image_**
}
Then run the remaining steps and let the script error.

To enable PSRemoting, in the Azure Portal use the RUN command on ws2019-wac-vm
![1](https://user-images.githubusercontent.com/47788394/103767390-6d698080-5018-11eb-8718-9f2864ea8da0.JPG)

To RDP to ws2019-wac-vm you need to add an inbound rule to ws2019-wac-vm NSG (its already open at the subnet, but not the nic)
![2](https://user-images.githubusercontent.com/47788394/103767699-039da680-5019-11eb-8567-cc75af48c092.JPG)

Then use RDP to connect to the Public IP address of ws2019-wac-vm and manually install WAC.

You can then continue and complete the remainder of the lab from task 2 onwards.
![3](https://user-images.githubusercontent.com/47788394/103767982-8b83b080-5019-11eb-9e07-af446c203c6b.JPG)

**Comment by Miller6025** [comment]
Yup same error with certificate!  Students will struggle with this and it should be corrected **IMMEDIATELY** in the course materials and lab instructions!

**Comment by TJGitHubUser** [comment]
Fixed.
