### ISSUE TITLE
Lab 4

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#12]
# Module: 4
#### Step: all

Description of issue
Why is this using automatic provisioning?
The instructions indicate a 30min wait from enabling the autoprovisioning before you can change the event collection level, this is taking well oven an hour and you then don't get to see security event generated as after 2 hours still waiting for the agent to install....
The later step where you manually install the agent onto the onprem server and then indicates that there may be several mins wait, that alert came through straight away.

Lab needs splitting into 2, 1st done early in the module to onboard SC with manual agent install, and then 2nd lab to install onto onprem and test both.
Repro steps:

1.
1.
1.

**Comment by Miller6025** [comment]
I have the same issues, PLUS the lab instructions do not reflect what students will see...When I ran through the labs after creating the workspace and performing "Upgrade" no Data Connectors appeared in the blade.

**Comment by TJGitHubUser** [comment]
Thanks for suggestion about splitting the exercises. Will consider incorporating in a future revision.
Lab instructions fixed to reflect the UI.
