### ISSUE TITLE
Lab 04 - Unworkable

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#15]
# Module: 04
#### Step: MOST

Description of issue

The Security Center has changed so much that the instructions are now almost useless.

In addition there is  a 30 minute wait when you enable auto provisioning... this is not acceptable The prep guide Allocates a TOTAL of 40 minutes to the whole lab!

Examples
There is no longer  a Data collection section on the Settings Blade
There is no longer a Compute and Apps section on the Main Security center blade

Repro steps:

1.
1.
1.

**Comment by TJGitHubUser** [comment]
Instructions have been updated to match current Security Center. As far as changing the timing of the lab…. Will look at revising timeline estimates when we do a course revision.
