### ISSUE TITLE
Course team enquiry

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#16]
Are any of these issues being looked at by the course team?

# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by djcmct** [comment]
I got fed up of waiting so raised a ticket in MCT Support

https://trainingsupport.microsoft.com/en-us/tcmct/forum/all/ws-012-github-repo-not-being-maintained/fc97546f-5bbb-4955-a3d0-0966fea7e8ef

This is now, being addressed, no indication of time frame, but, at least its now moving forward

**Comment by TJGitHubUser** [comment]
Lab issues are now being looked at on a more regular cadence. Many of the issues listed in this repo have now been resolved, although there are a few being worked on or still to be addressed.
