### ISSUE TITLE
Module 4 Lab

### ISSUE THREAD

**Issue by rtrader58** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#18]
# Module: 04
#### Step: 00

Lab instruction are not correct with current Security Center Enviornment.

Labs do not work as written.

**Comment by TJGitHubUser** [comment]
Fixed.

**Comment by rtrader58** [comment]
Thank you for the update.



Rick Trader

Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Tony Jamieson ***@***.***>
Date: 4/7/21 11:00 AM (GMT-07:00)
To: MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS ***@***.***>
Cc: Rick Trader ***@***.***TT.com>, Author ***@***.***>
Subject: Re: [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS] Module 4 Lab (#18)


Closed #18<https://github.com/MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS/issues/18>.
