### ISSUE TITLE
Data Collection has been renamed Auto Provisioning and the options are different now. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#2]
#   Lab/Demo: 04
####   Step: 02

Description of issue
The previous steps read: In Security Center, select Pricing & settings, select your subscription, and then select Data Collection.
This has now been changed to Auto Provisioning and the options are different for subsequent steps. 

![2020-11-17_183247](https://user-images.githubusercontent.com/62302805/99463236-52756c80-2903-11eb-93c7-dd669d33ce92.JPG)

Repro steps:
https://github.com/MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS/blob/master/Instructions/Labs/LAB_AK_04_Using_Azure_Security_Center_in_hybrid_scenarios.md

**Comment by TJGitHubUser** [comment]
Fixed. Ex 2, Task 2, Step 2: the Data Provisioning menu has been changed to Auto Provisioning.
