### ISSUE TITLE
Summary of outstanding issues as of 18th February 2021

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#23]
Not sure if the repo is being maintained so have summarised the effect of the recent updates to the labs (pull request 20)

Good news first, updates that have been made to the lab instructions means that all labs now match appropriate UI’s so all steps can be followed, (Hopefully LAK's to follow)

The other good news is that Lab 02, Lab 05, Lab 06 & Lab 08 all work without issue.

The bad news,

Lab 04 simply doesn’t work as a lab in a training environment, its intended purpose to demonstrate the use of Azure Security Centre to capture events on both Azure & OnPrem vm’s is great except for the length of time it actually takes for the Security Centre and the required Log Analytics workspace to become useable after enabling.
When you get around 5 min’s in to the lab and into Ex 2 there is a note to say that it may take 30 mins before you can perform the next step (and you cannot continue), in reality, it takes around 3 hours before you can continue. A 30 min wait is manageable if arranged around a lunch break, a 3 hour wait is impossible to manage.
I’d suggest that there should be a Lab for Mod 1 that introduces the tools used in Azure and that the Security Centre/Log Analytics enablement should take place then so that it is ready for Lab 04.

Lab 3 has a couple of issues, 
Ex 1 & Ex2 create resources in Azure to connect an OnPrem Server to with an Azure Network Adapter, the instructions ask you to pick an Azure region, I’ve attempted this lab many times using different regions, and the only region that works is East US, so could the instructions be updated to this?

Ex 3 gets you to create an Azure Admin Gateway, I’ve used the updated Allfiles but still run in to the same issues,
Ex 3 Task 1 Step 6 needs to be updated to 
$scriptParams = @{
ResourceGroupName = $rgName
Name = 'ws2019-wac-vm'
VirtualNetworkName = $vnetName
SubnetName = $subnetName
GenerateSslCert = $true
size = $size
image = $image
}
Without the addition of the size and image variables you get a VM running Server 2016 of too small a size.

The biggest issue is when running the subsequent steps 7 to 9. The provided Deploy-WACAzVM.ps1 includes the use of the invoke-azvmcommand cmdlet.
Something changed in Azure Cloud Shell around December 2020 where the use of self signed certificates was no longer supported by this cmdlet, which means that the entire remainder of the lab cannot be completed.
So either the script needs to be changed to achieve the same result using a different method that is supported for self signed certs, or modified to create and utilise a trusted certificate from Azure key Vault.
This has been documented https://github.com/MicrosoftDocs/azure-docs/issues/68262 but without resolution.

The same issue effects Lab 07, Ex 3 task 2 cannot be performed due to the use of the invoke-azcommand cmdlet.

**Comment by djcmct** [comment]
Update to the issues around self signed certs in lab 3 & 7.
Running **install-module pswsman** and then **Disable-WSManCertVerification -All** before will allow the self signed certs to validate without error

**Comment by TJGitHubUser** [comment]
Issues have been addressed.
