### ISSUE TITLE
Issue in lab 07 serv

### ISSUE THREAD

**Issue by cebesten** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#24]
# Module: 07
#### Step: 03

Description of issue
after typing cmd
Invoke-AzVMCommand -Name 'Mod07Target' -ResourceGroupName 'ws2019-06-rg1' -ScriptBlock {get-service win*} -Credential $Cred
Having an error line 1112 [mod07target-20c029.eastus.cloudapp.azure.com] Connecting to remote server
     | mod07target-20c029.eastus.cloudapp.azure.com failed with the following error message : error:1416F086:SSL
     | routines:tls_process_server_certificate:certificate

and with the cmnd 
Enter-AzVM -Name Mod07Target -ResourceGroupName ws2019-06-rg1 -Credential $Cred
having error 
Line 958 
Connecting to remote server mod07target-20c029.eastus.cloudapp.azure.com failed with the following error message :
     | error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed For more information, see the
     | about_Remote_Troubleshooting Help topic.

![image](https://user-images.githubusercontent.com/48234458/109109422-2b8cba80-76ea-11eb-8fa0-522a8724a7b0.png)

FYI my resourceGroupName is with 06..
the others commands work fine

Repro steps:

1. Following steps in lab
1.
1.

**Comment by TJGitHubUser** [comment]
There was an issue with this lab due to a change that took place last December, affecting the use of PS remoting and required a change in the lab instructions to disable certificate verification for PS remoting. This should have fixed the issue you were having on lab 7. This same issue affected lab 3.
