### ISSUE TITLE
Ex4, Task 2: Possible Stop Error

### ISSUE THREAD

**Issue by garjen55** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#25]
# Module: 04
#### Steps: 07-10

Ex4, Task 2: Possible Stop Error
![StopError-WS012-Mod4-April2021-a](https://user-images.githubusercontent.com/46939028/113657189-04b79180-9663-11eb-90e3-a7f6c1b76ff4.jpg)
![StopError-WS012-Mod4-April2021-b](https://user-images.githubusercontent.com/46939028/113657191-05502800-9663-11eb-9488-aa5255aed3b3.jpg)

I couldn’t complete the last task “Task 2: Validate the Security Center capabilities for on-premises servers”. Sea-Svr1 never showed in the Inventory or triggered a security alert.

**Comment by sbolan** [comment]
Lab worked fine for me in class last week (I was also using Labs On Demand).  Note that when you enable the Azure Defender feature, the LoD mentions that it may take up to 30 minutes to fully enable, my experience has been that this can take several hours (2-3).
![image](https://user-images.githubusercontent.com/14906689/113797213-70a70200-9716-11eb-9fce-c70364f225f1.png)

**Comment by garjen55** [comment]
That must have been it. - Just needed to give it more time.Thanks,Garrett
    On Tuesday, April 6, 2021, 08:27:30 PM CDT, Shawn Bolan ***@***.***> wrote:  
 
 


Lab worked fine for me in class last week (I was also using Labs On Demand). Note that when you enable the Azure Defender feature, the LoD mentions that it may take up to 30 minutes to fully enable, my experience has been that this can take several hours (2-3).
