### ISSUE TITLE
Module 8 - template unavailable

### ISSUE THREAD

**Issue by sbolan** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#28]
# Module: 08
#### Step: 07

Description of issue
The referenced Quickstart template from Github is not available.
https://github.com/Azure/azure-quickstart-templates/tree/master/301-nested-vms-in-virtual-network
Browsing to the template via the Quickstart GUI page and attempting to deploy from there does not work either.
https://azure.microsoft.com/en-us/resources/templates/301-nested-vms-in-virtual-network/

Without this template, the entire lab is broken.

Repro steps:

1.
1.
1.

**Comment by ZekeStarr** [comment]
It looks like it was moved into the demos folder this morning: https://github.com/Azure/azure-quickstart-templates/tree/master/demos/nested-vms-in-virtual-network

**Comment by TJGitHubUser** [comment]
The Quickstart Templates went through a major reshuffle last week , and it impacted quite a few labs, not just WS-012. We authorized a merge on a pull request to account for the new URL/location of the 301-nested-vms-in-virtual-network template. This is now fixed.
