### ISSUE TITLE
Two errors in LAB_AK_03 document

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#3]
# Module: 00
## Lab/Demo: 03
Exercise 2
#### Step: 00

Description of issue

In file 'LAB_AK_03_Using_Windows_Admin_Center_in_hybrid_scenarios.md' In Exercise 2, Task 1, Step 2 it is referenced:
'If prompted, sign in as **CONTOSO\\Student** with **Pa55w.rd1234** as the password.'

- This should CONTOSO\Administrator with password of Pa55w.rd

In same file, in Exercise 2, Task 2, Step 1 it is referenced:
 'navigate back to the lon-srv2.contoso.com'

- This should be sea-svr2.contoso.com

**Comment by TJGitHubUser** [comment]
Fixed.
