### ISSUE TITLE
Lab 03: 'Virtual Network' field not being populated in 'Add Network Settings' field when West Europe region is used.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#4]
# Module: 00
## Lab/Demo: 03
Exercise 2
#### Step: 03

Description of issue

When using the West Europe region for this lab, despite no errors in creating any of the previous resource groups or other resources, the server admin tool is seemingly unable to populate its Virtual Network field with the 'ws2019-m03-vnet'.  

I have seen 3 consecutive repros with this exact failed behavior, and in each case the exact resource, with the exact name, WAS present in the azure pass account utilized.  No errors were seen in any previous step, and all other instructions appeared to complete successfully.

Repro steps:

Run the lab to this point using West Europe as a region.

NOTE: If one uses East US, the issue does not occur.

**Comment by djcmct** [comment]
its also worth mentioning that it takes a good 10 mins after the VM has finished deploying for the WAC to populate the Virtual Network Field even using East US

**Comment by TJGitHubUser** [comment]
Fixed. Changed to specify East US region.
