### ISSUE TITLE
Module 06: Exercise 5 needs re-write/clarifications after Azure Security Center changes.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#6]
# Module: 06
## Lab/Demo: 00
Exercise 5
#### Step: 00

Description of issue
Azure Security Center has changed since instructions were written, and after trying to identify steps that would work in the new Azure Security Center to enable JIT for VM I have given up.  Would appreciate if Course Author could update instructions appropriately.

**Comment by djcmct** [comment]
Me too.

I ended up going to the VM and turning on JIT on the connect blade

**Comment by TJGitHubUser** [comment]
Instructions fixed.
