### ISSUE TITLE
Module 7: IE11 no longer allows Edge 'Try Now' functionality.  Must manually download.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#7]
# Module: 07
#### Step: 00

Description of issue

I believe the functionality used from the Edge upgrade site has changed such that there is not a 'download now' link from there that works suyccessfully w/IE11.  Instead it says 'Try Now' and when you attempt to utilize that in IE11 it tells you you need another app to deal with that sort of link, and helpfully suggests Edge.  Ironic, no?  :)

Instead, for now, one can still download a functional Edge version using *actual* download functionality from here:  https://www.microsoft.com/en-us/edge/business/download

 -- Instructions should be updated to take this into account.

**Comment by Miller6025** [comment]
My solution was to have the students download and USE Google Chrome!

**Comment by TJGitHubUser** [comment]
Fixed. Added a note regarding issue installing Edge browser
