### ISSUE TITLE
Module 07: Exercise 4/Task 1 'EnableRemotePS' runs, but errors due to previous configuration

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS#9]
# Module: 07
## Lab/Demo: 00
Exercise 4
#### Step: 00

Description of issue

Although yes, this script runs - it will kick out an error at the end indicating:
![image](https://user-images.githubusercontent.com/49700217/103370049-a5a11a00-4a80-11eb-94a0-cdfb284b0276.png)

This would presumably be because the previous exercises already set WS remoting config.  Is this something where the script could be directed at (perhaps) Mod07Gateway VM instead, so it does not error out?  Or, alternatively, add a previous step to delete the preexisting remoting config on this VM such that it does not error.

Students taking this course will often see such error, and not necessarily realize the 'why' of it, and it makes for confusion.
   
Repro steps:

1.
1.
1.

**Comment by TJGitHubUser** [comment]
There was an issue with this lab due to a change that took place last affecting the use of PS remoting and required a change in the lab instructions to disable certificate verification for PS remoting. This should have fixed the issue you were having on lab 7. This same issue affected lab 3.
